services:

  db:
    container_name: home-drive-db
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: homedrive
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - home-drive:/var/lib/postgresql/data
    networks:
      - db-network


networks:
  db-network:
    driver: bridge
volumes:
  home-drive:

